# Generated by Django 5.1.7 on 2026-06-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0011_hadithdocumentupload'),
        ('user_management', '0002_user_last_email_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_hadith_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hadith.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_hadith_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='current_verse_ayah',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='current_verse_surah',
            field=models.IntegerField(default=1),
        ),
    ]
