# Generated by Django 5.1.7 on 2026-06-25 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0011_hadithdocumentupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hadithdocumentupload',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hadith_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
