# Generated by Django 5.1.7 on 2026-01-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_ayat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ayat',
            unique_together={('para', 'surah', 'ayat_number')},
        ),
    ]
