# Generated by Django 5.1.7 on 2026-01-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_ayat_updated_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ayat',
        ),
    ]
