# Generated by Django 5.1.7 on 2026-07-09 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0010_question_download_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='updated_by_manual',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mufti'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_by_manual',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mufti'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
