# Generated by Django 5.1.7 on 2026-02-05 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.IntegerField()),
                ('ayat_number', models.IntegerField()),
                ('text', models.TextField()),
                ('tafsir', models.TextField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='ayat_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('surah', 'ayat_number')},
            },
        ),
        migrations.CreateModel(
            name='Tafseer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('para', models.IntegerField(choices=[(1, 'Para 1'), (2, 'Para 2'), (3, 'Para 3'), (4, 'Para 4'), (5, 'Para 5'), (6, 'Para 6'), (7, 'Para 7'), (8, 'Para 8'), (9, 'Para 9'), (10, 'Para 10'), (11, 'Para 11'), (12, 'Para 12'), (13, 'Para 13'), (14, 'Para 14'), (15, 'Para 15'), (16, 'Para 16'), (17, 'Para 17'), (18, 'Para 18'), (19, 'Para 19'), (20, 'Para 20'), (21, 'Para 21'), (22, 'Para 22'), (23, 'Para 23'), (24, 'Para 24'), (25, 'Para 25'), (26, 'Para 26'), (27, 'Para 27'), (28, 'Para 28'), (29, 'Para 29'), (30, 'Para 30')])),
                ('surah', models.IntegerField()),
                ('ayat_number', models.IntegerField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], default='en', max_length=5)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('para', 'surah', 'ayat_number', 'author', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('para', models.IntegerField(choices=[(1, 'Para 1'), (2, 'Para 2'), (3, 'Para 3'), (4, 'Para 4'), (5, 'Para 5'), (6, 'Para 6'), (7, 'Para 7'), (8, 'Para 8'), (9, 'Para 9'), (10, 'Para 10'), (11, 'Para 11'), (12, 'Para 12'), (13, 'Para 13'), (14, 'Para 14'), (15, 'Para 15'), (16, 'Para 16'), (17, 'Para 17'), (18, 'Para 18'), (19, 'Para 19'), (20, 'Para 20'), (21, 'Para 21'), (22, 'Para 22'), (23, 'Para 23'), (24, 'Para 24'), (25, 'Para 25'), (26, 'Para 26'), (27, 'Para 27'), (28, 'Para 28'), (29, 'Para 29'), (30, 'Para 30')])),
                ('surah', models.IntegerField()),
                ('ayat_number', models.IntegerField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], max_length=5)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('para', 'surah', 'ayat_number', 'language', 'author')},
            },
        ),
    ]
