# Generated by Django 5.1.7 on 2026-02-05 10:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayat',
            name='tafsir',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ayat',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
