# Generated by Django 5.1.7 on 2026-02-13 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_customfont'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayat',
            options={'ordering': ['surah', 'ayat_number']},
        ),
        migrations.AlterModelOptions(
            name='customfont',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['surah', 'ayat_number']},
        ),
        migrations.AlterUniqueTogether(
            name='tafseer',
            unique_together={('surah', 'ayat_number', 'author', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('surah', 'ayat_number', 'language', 'author')},
        ),
        migrations.AddField(
            model_name='customfont',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable / Disable this font'),
        ),
        migrations.AlterField(
            model_name='ayat',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ayats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customfont',
            name='file',
            field=models.FileField(help_text='Upload .ttf or .otf font file', upload_to='custom_fonts/'),
        ),
        migrations.AlterField(
            model_name='customfont',
            name='name',
            field=models.CharField(help_text='Font name shown in editor (e.g. Al Mushaf)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tafseer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tafseers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tafseer',
            name='para',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='para',
        ),
    ]
